In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

week2-4-numpy****

In [ ]:
import numpy as np

In [ ]:
#element are refered to as arrays in numpy
a = np.array([1,2,3])

In [ ]:
a

In [ ]:
#Get shape of array
#shape gives number of things in the array
a.shape

In [ ]:
#Get dimension of array
a.ndim

In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])

In [ ]:
b.ndim

In [ ]:
b.shape

In [19]:
#slicing the array/matrix row by column
#counting starts from zero though
b[1,2]

6

In [25]:
#get a specific row
# : means everything from the column or row
b[0,:]

array([1, 2, 3])

In [24]:
#get a specific column
b[:,2]

array([3, 6])

In [26]:
b[0,1:6]

array([2, 3])

In [28]:
#last 2 means move by 2
b[0,1:2:2]

array([2])

In [16]:
c = np.array([[[1,2,3],
             [4,5,6],
             [7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [17]:
c.shape

(1, 3, 3)

In [18]:
#one row is an array while multiple rows are matrix
c.ndim

3

In [55]:
#all zero
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [59]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [60]:
#numbers other than ones and zeros
np.full((3,5), 59)

array([[59, 59, 59, 59, 59],
       [59, 59, 59, 59, 59],
       [59, 59, 59, 59, 59]])

In [61]:
#random floats
np.random.rand(4,2,4)

array([[[0.53858936, 0.82409267, 0.41339082, 0.68486138],
        [0.66908153, 0.21097434, 0.51428311, 0.09568776]],

       [[0.59776736, 0.9035613 , 0.15895733, 0.86000137],
        [0.34326889, 0.42027089, 0.20135533, 0.66939584]],

       [[0.95651622, 0.97619921, 0.65925784, 0.68192546],
        [0.56719588, 0.59088334, 0.21305683, 0.06050332]],

       [[0.27348006, 0.46059164, 0.10872621, 0.8118806 ],
        [0.37191003, 0.16909678, 0.33289497, 0.90323977]]])

In [52]:
z = [[1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25],
    [26,27,28,29,30]]

In [37]:
z = [1,9,15,21]

In [66]:
#random integers
# 0,10 says give numbers btw 0 and 10
np.random.randint(0,10, size=(9,9))

array([[1, 5, 2, 8, 4, 1, 9, 6, 1],
       [3, 1, 2, 6, 0, 6, 8, 6, 2],
       [9, 5, 7, 0, 9, 5, 9, 3, 4],
       [4, 8, 6, 9, 7, 6, 4, 9, 6],
       [6, 4, 6, 2, 0, 0, 6, 1, 2],
       [2, 9, 2, 3, 2, 1, 8, 8, 9],
       [2, 0, 8, 7, 4, 8, 0, 1, 5],
       [0, 7, 8, 3, 1, 8, 0, 0, 7],
       [2, 7, 1, 3, 8, 7, 1, 6, 0]])

In [67]:
np.random.randint(0,10, size=(3,3))

array([[8, 5, 1],
       [5, 8, 8],
       [1, 9, 8]])

In [69]:
#scale matrix; calculating matrix/array with a number
a = np.array([1,2,3,4,5])
a*2

array([ 2,  4,  6,  8, 10])

In [80]:
#multiple matrix with matrix
a = np.array([1,2,3,4,5])
b = np.array([1,0,1,0])
a*b

array([1, 0, 3, 0])

In [76]:
np.random.randint(0,2, size=(5,5))

array([[1, 0, 1, 0, 0],
       [1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1],
       [1, 1, 1, 0, 0],
       [1, 0, 0, 0, 0]])

In [113]:
one=np.ones((5,5))
one[1:4, 1:4] = 0
one[2, 2] = 9

print(one)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
